# Generated by Django 5.2.7 on 2025-10-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
